"""Asterisk implementation of the VoIP platform interface.

Pure, deterministic renderers. Same input always produces byte-identical
output (sorted keys, stable section order) so configs are diff-friendly.
"""
from __future__ import annotations

from ..base import VoipPlatform


class AsteriskPlatform(VoipPlatform):
    name = "asterisk"

    def config_dir(self) -> str:
        return "/etc/asterisk"

    def service_unit(self) -> str:
        return "asterisk"

    def reload_cmd(self) -> list[str]:
        return ["asterisk", "-rx", "core reload"]

    # ---------- renderers ----------
    def render_signalling_config(self, inv) -> str:
        endpoints = sorted(inv.endpoints, key=lambda e: e.extension)
        trunks = sorted(inv.trunks, key=lambda t: t.name)
        parts = [self._header(inv.server_name), self._transports(inv)]
        parts.append("; ----- Endpoints -----")
        parts.extend(self._endpoint_block(e) for e in endpoints)
        parts.append("; ----- Trunks -----")
        parts.extend(self._trunk_block(t) for t in trunks)
        return "\n".join(parts) + "\n"

    def render_dialplan(self, inv) -> str:
        endpoints = sorted(inv.endpoints, key=lambda e: e.extension)
        lines = [
            "; ============================================================",
            f"; extensions.conf — generated by AsterOps for {inv.server_name}",
            "; ============================================================",
            "",
            "[globals]",
            f"RTPSTART={inv.rtp_start}",
            f"RTPEND={inv.rtp_end}",
            "",
            "[from-internal]",
            "exten => _X.,1,NoOp(Internal call to ${EXTEN})",
            " same => n,Set(__DIALOPTS=tT)",
            " same => n,Dial(PJSIP/${EXTEN},30,${DIALOPTS})",
            " same => n,Hangup()",
            "",
            "[from-trunk]",
            "exten => _X.,1,NoOp(Inbound call to ${EXTEN})",
            " same => n,Dial(PJSIP/${EXTEN},30)",
            " same => n,Hangup()",
            "",
            "; ----- Per-extension hints (BLF) -----",
        ]
        for e in endpoints:
            lines.append(f"exten => {e.extension},hint,PJSIP/{e.extension}")
        return "\n".join(lines) + "\n"

    def render_rtp_config(self, inv) -> str:
        return (
            "; ============================================================\n"
            f"; rtp.conf — generated by AsterOps for {inv.server_name}\n"
            "; ============================================================\n"
            "[general]\n"
            f"rtpstart={inv.rtp_start}\n"
            f"rtpend={inv.rtp_end}\n"
            "strictrtp=yes\n"
            "icesupport=no\n"
        )

    # ---------- helpers ----------
    @staticmethod
    def _header(server_name: str) -> str:
        return (
            "; ============================================================\n"
            f"; pjsip.conf — generated by AsterOps for {server_name}\n"
            "; DO NOT EDIT BY HAND. This file is overwritten by the agent.\n"
            "; ============================================================\n"
        )

    @staticmethod
    def _transports(inv) -> str:
        blocks: list[str] = []
        if not inv.tls_only:
            blocks.append(
                "[transport-udp]\ntype=transport\nprotocol=udp\nbind=0.0.0.0:5060\n"
            )
            blocks.append(
                "[transport-tcp]\ntype=transport\nprotocol=tcp\nbind=0.0.0.0:5060\n"
            )
        blocks.append(
            "[transport-tls]\ntype=transport\nprotocol=tls\nbind=0.0.0.0:5061\n"
            f"cert_file={inv.cert_file}\npriv_key_file={inv.priv_key_file}\n"
            "method=tlsv1_2\nverify_client=no\nverify_server=no\n"
            "require_client_cert=no\n"
        )
        return "\n".join(blocks)

    @staticmethod
    def _endpoint_block(e) -> str:
        allow = ",".join(e.codecs) if e.codecs else "ulaw"
        enc = "sdes" if e.srtp_required else "no"
        transport = "transport-tls" if e.tls_required else e.transport
        password = e.secret or "<set-by-agent>"
        name = e.display_name or e.extension
        return (
            f"; --- {e.extension} ({name}) ---\n"
            f"[{e.extension}]\ntype=endpoint\ncontext={e.context}\n"
            f"disallow=all\nallow={allow}\n"
            f"auth={e.extension}-auth\naors={e.extension}\n"
            f"transport={transport}\nmedia_encryption={enc}\n"
            "media_encryption_optimistic=no\nforce_rport=yes\n"
            "rewrite_contact=yes\nrtp_symmetric=yes\ndirect_media=no\n\n"
            f"[{e.extension}-auth]\ntype=auth\nauth_type=userpass\n"
            f"username={e.extension}\npassword={password}\n\n"
            f"[{e.extension}]\ntype=aor\nmax_contacts={e.max_contacts}\n"
            "remove_existing=yes\nqualify_frequency=60\n"
        )

    @staticmethod
    def _trunk_block(t) -> str:
        enc = "sdes" if t.srtp_required else "no"
        user = t.username or ""
        return (
            f"; --- trunk: {t.name} ---\n"
            f"[{t.name}]\ntype=endpoint\ncontext=from-trunk\n"
            "disallow=all\nallow=ulaw,alaw,g722\n"
            f"outbound_auth={t.name}-auth\naors={t.name}\n"
            f"transport={t.transport}\nmedia_encryption={enc}\n"
            f"from_user={user}\n\n"
            f"[{t.name}-auth]\ntype=auth\nauth_type=userpass\n"
            f"username={user}\npassword=<set-by-agent>\n\n"
            f"[{t.name}]\ntype=aor\ncontact=sip:{t.host}:{t.port}\n"
            "qualify_frequency=60\n\n"
            f"[{t.name}-identify]\ntype=identify\nendpoint={t.name}\n"
            f"match={t.host}\n"
        )