/**
 * Pure deterministic Asterisk pjsip.conf renderer.
 * Same input always produces byte-identical output (sorted keys, stable section order).
 * Pure TS — no I/O, no env access. Safe to call from client OR server.
 */

export interface RenderEndpoint {
  extension: string;
  display_name?: string | null;
  context: string;
  codecs: string[];
  transport: string;
  tls_required: boolean;
  srtp_required: boolean;
  max_contacts: number;
}

export interface RenderTrunk {
  name: string;
  host: string;
  port: number;
  username?: string | null;
  transport: string;
  srtp_required: boolean;
}

export interface RenderInput {
  serverName: string;
  tlsOnly: boolean;
  certFile?: string;
  privKeyFile?: string;
  endpoints: RenderEndpoint[];
  trunks: RenderTrunk[];
}

const HEADER = (serverName: string) =>
  `; ============================================================
; pjsip.conf — generated by AsterOps for ${serverName}
; DO NOT EDIT BY HAND. This file is overwritten by the agent.
; ============================================================
`;

function transportBlock(input: RenderInput): string {
  const blocks: string[] = [];
  if (!input.tlsOnly) {
    blocks.push(`[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
`);
    blocks.push(`[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060
`);
  }
  blocks.push(`[transport-tls]
type=transport
protocol=tls
bind=0.0.0.0:5061
cert_file=${input.certFile ?? "/etc/asterisk/keys/asterisk.crt"}
priv_key_file=${input.privKeyFile ?? "/etc/asterisk/keys/asterisk.key"}
method=tlsv1_2
verify_client=no
verify_server=no
require_client_cert=no
`);
  return blocks.join("\n");
}

function endpointBlocks(e: RenderEndpoint): string {
  const allow = e.codecs.length > 0 ? e.codecs.join(",") : "ulaw";
  const enc = e.srtp_required ? "sdes" : "no";
  const transport = e.tls_required ? "transport-tls" : e.transport;
  return `; --- ${e.extension}${e.display_name ? ` (${e.display_name})` : ""} ---
[${e.extension}]
type=endpoint
context=${e.context}
disallow=all
allow=${allow}
auth=${e.extension}-auth
aors=${e.extension}
transport=${transport}
media_encryption=${enc}
media_encryption_optimistic=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes
direct_media=no

[${e.extension}-auth]
type=auth
auth_type=userpass
username=${e.extension}
password=<set-by-agent>

[${e.extension}]
type=aor
max_contacts=${e.max_contacts}
remove_existing=yes
qualify_frequency=60
`;
}

function trunkBlocks(t: RenderTrunk): string {
  const enc = t.srtp_required ? "sdes" : "no";
  return `; --- trunk: ${t.name} ---
[${t.name}]
type=endpoint
context=from-trunk
disallow=all
allow=ulaw,alaw,g722
outbound_auth=${t.name}-auth
aors=${t.name}
transport=${t.transport}
media_encryption=${enc}
from_user=${t.username ?? ""}

[${t.name}-auth]
type=auth
auth_type=userpass
username=${t.username ?? ""}
password=<set-by-agent>

[${t.name}]
type=aor
contact=sip:${t.host}:${t.port}
qualify_frequency=60

[${t.name}-identify]
type=identify
endpoint=${t.name}
match=${t.host}
`;
}

export function renderPjsip(input: RenderInput): string {
  const endpoints = [...input.endpoints].sort((a, b) =>
    a.extension.localeCompare(b.extension),
  );
  const trunks = [...input.trunks].sort((a, b) => a.name.localeCompare(b.name));

  return [
    HEADER(input.serverName),
    "; ----- Transports -----",
    transportBlock(input),
    "; ----- Endpoints -----",
    endpoints.map(endpointBlocks).join("\n"),
    "; ----- Trunks -----",
    trunks.map(trunkBlocks).join("\n"),
  ].join("\n");
}

export function renderHardeningScript(opts: {
  serverName: string;
  fail2banEnabled: boolean;
  iptablesEnabled: boolean;
  amiLockdown: boolean;
  rtpStart: number;
  rtpEnd: number;
  sshHardening: boolean;
}): string {
  const lines: string[] = [
    "#!/usr/bin/env bash",
    "# ============================================================",
    `# AsterOps hardening bundle — ${opts.serverName}`,
    "# Review before running. Idempotent. Requires root.",
    "# ============================================================",
    "set -euo pipefail",
    "if [[ $EUID -ne 0 ]]; then echo 'Run as root' >&2; exit 1; fi",
    "",
    "BACKUP_DIR=/var/backups/asterops/$(date +%Y%m%d-%H%M%S)",
    'mkdir -p "$BACKUP_DIR"',
    "echo \"[+] Backups will be stored in $BACKUP_DIR\"",
    "",
  ];

  if (opts.iptablesEnabled) {
    lines.push(
      "# --- iptables / firewall ---",
      "echo '[+] Configuring firewall rules'",
      "iptables -F INPUT",
      "iptables -P INPUT DROP",
      "iptables -A INPUT -i lo -j ACCEPT",
      "iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT",
      "iptables -A INPUT -p tcp --dport 22 -j ACCEPT      # SSH",
      "iptables -A INPUT -p tcp --dport 5061 -j ACCEPT    # SIP/TLS",
      "# SIP UDP/TCP intentionally NOT opened (TLS-only)",
      `iptables -A INPUT -p udp --dport ${opts.rtpStart}:${opts.rtpEnd} -j ACCEPT  # RTP`,
      "iptables -A INPUT -p icmp -j ACCEPT",
      "iptables-save > /etc/iptables/rules.v4 2>/dev/null || true",
      "",
    );
  }

  if (opts.fail2banEnabled) {
    lines.push(
      "# --- fail2ban jail for Asterisk ---",
      "echo '[+] Installing fail2ban jail'",
      "apt-get update -y && apt-get install -y fail2ban || true",
      "cat > /etc/fail2ban/jail.d/asterisk.conf <<'EOF'",
      "[asterisk-iptables]",
      "enabled  = true",
      "filter   = asterisk",
      "action   = iptables-allports[name=ASTERISK, protocol=all]",
      "logpath  = /var/log/asterisk/messages",
      "maxretry = 5",
      "findtime = 600",
      "bantime  = 86400",
      "EOF",
      "systemctl enable --now fail2ban",
      "systemctl restart fail2ban",
      "",
    );
  }

  if (opts.amiLockdown) {
    lines.push(
      "# --- AMI lockdown (bind to loopback only) ---",
      "echo '[+] Locking down Asterisk Manager Interface'",
      'cp /etc/asterisk/manager.conf "$BACKUP_DIR/" 2>/dev/null || true',
      "sed -i 's/^bindaddr.*/bindaddr = 127.0.0.1/' /etc/asterisk/manager.conf || true",
      "chown root:asterisk /etc/asterisk/manager.conf",
      "chmod 640 /etc/asterisk/manager.conf",
      "",
    );
  }

  if (opts.sshHardening) {
    lines.push(
      "# --- SSH hardening ---",
      "echo '[+] Hardening SSH'",
      'cp /etc/ssh/sshd_config "$BACKUP_DIR/" 2>/dev/null || true',
      "sed -i 's/^#\\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config",
      "sed -i 's/^#\\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config",
      "systemctl restart sshd",
      "",
    );
  }

  lines.push(
    "# --- File permissions ---",
    "chown -R root:asterisk /etc/asterisk",
    "chmod -R 640 /etc/asterisk/*.conf",
    "",
    "echo '[OK] Hardening complete.'",
  );

  return lines.join("\n") + "\n";
}