/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAgentStatusRouteImport } from './routes/api/public/agent/status'
import { Route as ApiPublicAgentEnrollRouteImport } from './routes/api/public/agent/enroll'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentStatusRoute = ApiPublicAgentStatusRouteImport.update({
  id: '/api/public/agent/status',
  path: '/api/public/agent/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentEnrollRoute = ApiPublicAgentEnrollRouteImport.update({
  id: '/api/public/agent/enroll',
  path: '/api/public/agent/enroll',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/status': typeof ApiPublicAgentStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/status': typeof ApiPublicAgentStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/status': typeof ApiPublicAgentStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/agent/enroll' | '/api/public/agent/status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/agent/enroll' | '/api/public/agent/status'
  id: '__root__' | '/' | '/api/public/agent/enroll' | '/api/public/agent/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAgentEnrollRoute: typeof ApiPublicAgentEnrollRoute
  ApiPublicAgentStatusRoute: typeof ApiPublicAgentStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/status': {
      id: '/api/public/agent/status'
      path: '/api/public/agent/status'
      fullPath: '/api/public/agent/status'
      preLoaderRoute: typeof ApiPublicAgentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/enroll': {
      id: '/api/public/agent/enroll'
      path: '/api/public/agent/enroll'
      fullPath: '/api/public/agent/enroll'
      preLoaderRoute: typeof ApiPublicAgentEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAgentEnrollRoute: ApiPublicAgentEnrollRoute,
  ApiPublicAgentStatusRoute: ApiPublicAgentStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
