/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicAgentStatusRouteImport } from './routes/api/public/agent/status'
import { Route as ApiPublicAgentEnrollRouteImport } from './routes/api/public/agent/enroll'
import { Route as ApiPublicAgentConfigsRouteImport } from './routes/api/public/agent/configs'
import { Route as ApiPublicAgentCdrRouteImport } from './routes/api/public/agent/cdr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentStatusRoute = ApiPublicAgentStatusRouteImport.update({
  id: '/api/public/agent/status',
  path: '/api/public/agent/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentEnrollRoute = ApiPublicAgentEnrollRouteImport.update({
  id: '/api/public/agent/enroll',
  path: '/api/public/agent/enroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentConfigsRoute = ApiPublicAgentConfigsRouteImport.update({
  id: '/api/public/agent/configs',
  path: '/api/public/agent/configs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentCdrRoute = ApiPublicAgentCdrRouteImport.update({
  id: '/api/public/agent/cdr',
  path: '/api/public/agent/cdr',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/agent/cdr': typeof ApiPublicAgentCdrRoute
  '/api/public/agent/configs': typeof ApiPublicAgentConfigsRoute
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/status': typeof ApiPublicAgentStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/agent/cdr': typeof ApiPublicAgentCdrRoute
  '/api/public/agent/configs': typeof ApiPublicAgentConfigsRoute
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/status': typeof ApiPublicAgentStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/agent/cdr': typeof ApiPublicAgentCdrRoute
  '/api/public/agent/configs': typeof ApiPublicAgentConfigsRoute
  '/api/public/agent/enroll': typeof ApiPublicAgentEnrollRoute
  '/api/public/agent/status': typeof ApiPublicAgentStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/agent/cdr'
    | '/api/public/agent/configs'
    | '/api/public/agent/enroll'
    | '/api/public/agent/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/agent/cdr'
    | '/api/public/agent/configs'
    | '/api/public/agent/enroll'
    | '/api/public/agent/status'
  id:
    | '__root__'
    | '/'
    | '/api/public/agent/cdr'
    | '/api/public/agent/configs'
    | '/api/public/agent/enroll'
    | '/api/public/agent/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicAgentCdrRoute: typeof ApiPublicAgentCdrRoute
  ApiPublicAgentConfigsRoute: typeof ApiPublicAgentConfigsRoute
  ApiPublicAgentEnrollRoute: typeof ApiPublicAgentEnrollRoute
  ApiPublicAgentStatusRoute: typeof ApiPublicAgentStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/status': {
      id: '/api/public/agent/status'
      path: '/api/public/agent/status'
      fullPath: '/api/public/agent/status'
      preLoaderRoute: typeof ApiPublicAgentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/enroll': {
      id: '/api/public/agent/enroll'
      path: '/api/public/agent/enroll'
      fullPath: '/api/public/agent/enroll'
      preLoaderRoute: typeof ApiPublicAgentEnrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/configs': {
      id: '/api/public/agent/configs'
      path: '/api/public/agent/configs'
      fullPath: '/api/public/agent/configs'
      preLoaderRoute: typeof ApiPublicAgentConfigsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/cdr': {
      id: '/api/public/agent/cdr'
      path: '/api/public/agent/cdr'
      fullPath: '/api/public/agent/cdr'
      preLoaderRoute: typeof ApiPublicAgentCdrRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicAgentCdrRoute: ApiPublicAgentCdrRoute,
  ApiPublicAgentConfigsRoute: ApiPublicAgentConfigsRoute,
  ApiPublicAgentEnrollRoute: ApiPublicAgentEnrollRoute,
  ApiPublicAgentStatusRoute: ApiPublicAgentStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
